# setup selenium----->linked with chrome and firefox
---
version: '3.8'
services:
  myhub:
    image: selenium/hub
    ports:
      - 4444:4444
    container_name: myhub
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901:5900
    links:
      - myhub:selenium
    container_name: chrome
  firefox: 
    image: selenium/node-firefox-debug   
    ports:
      - 5902:5900
    links:
      - myhub:selenium
    container_name: firefox

...
